name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: |
        cd frontend && npm ci
        cd ../backend && npm ci
    - name: Run frontend tests
      run: cd frontend && npm test
    - name: Run backend tests
      run: cd backend && npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to production
      run: |
        # Add your deployment steps here
        # This could involve SSH into your server and pulling the latest changes
        # or deploying to a cloud platform like Heroku or DigitalOcean
      env:
        # Add any necessary secrets or environment variables
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}